// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4PNbsIG69GnY0Ep-CI1MUVI_XNaOV_mY',
    appId: '1:841823213387:web:b19d414a67f7c3b305face',
    messagingSenderId: '841823213387',
    projectId: 'syntrack-52802',
    authDomain: 'syntrack-52802.firebaseapp.com',
    storageBucket: 'syntrack-52802.firebasestorage.app',
    measurementId: 'G-3B42V3BT8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq2WTJzbLY3nO_cjqc54rK3BNsouW8Ypk',
    appId: '1:841823213387:android:61eafc000b949ed705face',
    messagingSenderId: '841823213387',
    projectId: 'syntrack-52802',
    storageBucket: 'syntrack-52802.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb8tZC4TAmsTsNWzIgpDkw_p0Sv2HtEWE',
    appId: '1:841823213387:ios:3eb3ed725775c01405face',
    messagingSenderId: '841823213387',
    projectId: 'syntrack-52802',
    storageBucket: 'syntrack-52802.firebasestorage.app',
    iosBundleId: 'com.example.syntrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb8tZC4TAmsTsNWzIgpDkw_p0Sv2HtEWE',
    appId: '1:841823213387:ios:3eb3ed725775c01405face',
    messagingSenderId: '841823213387',
    projectId: 'syntrack-52802',
    storageBucket: 'syntrack-52802.firebasestorage.app',
    iosBundleId: 'com.example.syntrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4PNbsIG69GnY0Ep-CI1MUVI_XNaOV_mY',
    appId: '1:841823213387:web:3bc87950d3d81b2705face',
    messagingSenderId: '841823213387',
    projectId: 'syntrack-52802',
    authDomain: 'syntrack-52802.firebaseapp.com',
    storageBucket: 'syntrack-52802.firebasestorage.app',
    measurementId: 'G-MQE1S31NDF',
  );
}
